#!/bin/sh
# (c) Copyright 2016 DataNexus Inc.  All Rights Reserved. 
# zookeeper deployment wrapper

export application=zookeeper   # application overlay to deploy
: "${AWS_PROFILE:=datanexus}" && export AWS_PROFILE="$AWS_PROFILE"    # sets this to a reasonable ~/.aws/credentials default
: "${AZURE_PROFILE:=datanexus}" && export AZURE_PROFILE="$AZURE_PROFILE"    # sets this to a reasonable ~/.azure/credentials default

if [ $# -eq 0 ] || [ "$1" = "-h" ] ; then
    printf "Usage:   deploy [-h]\\thelp\\n"
    printf "\\t deploy [FILE | TENANT PROJECT CLOUD REGION DOMAIN SSH_USER TENANT_PATH]\\tdeploy %s overlay with FILE configuration or with the specified values\\n" "$application"
    printf "Example: deploy datanexus demo aws us-east-1 development centos /tmp/datanexus\\n"
    printf "\\t deploy /tmp/configuration.yml\\n"
    exit 0
fi

# likely called by the orchestrator to just pass through everything
if [ $# -eq 4 ] && [ "$1" = "-e" ]; then
  ./provision-$application "$3" "$4" "$1" "$2"
# deploy zookeper as an overlay or a full deployment via configuration file
elif [ $# -eq 7 ] && [ -d "$7" ]; then
  ./provision-$application --tags "$application" -e "tenant=$1 project=$2 cloud=$3 region=$4 domain=$5 user=$6 tenant_config_path=$7"
elif [ $# -eq 1 ] && [ -f "$1" ] && [ -s "$1" ]; then
  ./provision-"$application" --tags "vm,$application" -e "configuration=$1"
fi
