# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- include_tasks: install-required-packages.yml
- include_tasks: add-zookeeper-user.yml
- include_tasks: install-apache-zookeeper.yml
- include_role: name=configure-zookeeper-nodes
- include_tasks: create-zookeeper-service.yml
- include_tasks: enable-zookeeper-service.yml
- include_tasks: start-zookeeper-service.yml
